# Generated by Django 5.1.3 on 2024-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_organized_by_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organized_by',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
